name: IP-Check
main: net.risenphoenix.jnk.ipcheck.IPcheck
version: 1.3.0_DEV_02
commands:
   c:
      description: Check for multi-accounting players via IP-Address or Player Name
      usage: /<command> [player_name | ip_address]
      permission: IPcheck.use
      permission-message: You don't have permission to use this command. Please contact your server administrator.